=begin
#Service API

#filters.

OpenAPI spec version: 1.0.0
Contact: anand@zerebral.co.in
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

module EventClient
  VERSION = '0.0.2'
end
