=begin
#Service API

#filters.

OpenAPI spec version: 1.0.0
Contact: anand@zerebral.co.in
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for EventClient::RegisterEventApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RegisterEventApi' do
  before do
    # run before each test
    @instance = EventClient::RegisterEventApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RegisterEventApi' do
    it 'should create an instance of RegisterEventApi' do
      expect(@instance).to be_instance_of(EventClient::RegisterEventApi)
    end
  end

  # unit tests for add_event
  # Register a new event
  # 
  # @param body Event object that needs to be added to the Index
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'add_event test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_event
  # Register a new event
  # 
  # @param body Event object that needs to be added to the Index
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_event test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
